default:
  cognito:
    group_name: "cognitoRdemo"
    oauth_flow: "code"
    base_cognito_url: "https://chi2labsdemo.auth.us-east-1.amazoncognito.com"
    app_client_id: "4dok9o23j7kp5nu7qm85q2s14c"
    app_client_secret: "1dd28q68r0nruccj1khdlhpr2h8mc5hmtnhfrvbfogn18l8rkisp"
    redirect_uri: "http://localhost:5000"
    redirect_uri_logout: "http://localhost:5000"
